// ============================================================
//  js/data.js — AUTO-GENERATED by build.py
//  Last built: 2026-03-22 11:00
//
//  ⚠  DO NOT edit this file directly.
//     • Edit posts in:       posts/research/*.md
//                            posts/blogs/*.md
//     • Edit personal info:  js/config.js
//     • Then run:            python build.py
// ============================================================

// Append posts to the SITE_DATA object already created by config.js
window.SITE_DATA.research = [
  {
    id: "research-3",
    emoji: "\ud83d\udd2d",
    image: "",
    date: "2025-03-15",
    title: "Deep Learning for Astronomical Image Classification",
    title_zh: "\u7528\u4e8e\u5929\u6587\u56fe\u50cf\u5206\u7c7b\u7684\u6df1\u5ea6\u5b66\u4e60",
    excerpt: "An investigation into convolutional neural networks applied to classifying galaxies and nebulae from telescope imagery.",
    excerpt_zh: "\u7814\u7a76\u5c06\u5377\u79ef\u795e\u7ecf\u7f51\u7edc\u5e94\u7528\u4e8e\u4ece\u671b\u8fdc\u955c\u56fe\u50cf\u4e2d\u5206\u7c7b\u661f\u7cfb\u548c\u661f\u4e91\u7684\u65b9\u6cd5\u3002",
    content: `
# Deep Learning for Astronomical Image Classification

## Abstract

This research explores the application of **convolutional neural networks (CNNs)** to classify astronomical objects from telescope imagery, achieving 94.3% accuracy on the benchmark dataset.

## Methodology

We trained a ResNet-50 model on the Galaxy Zoo dataset:

- 270,000 labeled galaxy images
- Data augmentation: rotation, flipping, color jitter
- Transfer learning from ImageNet weights

\`\`\`python
import torch, torchvision
model = torchvision.models.resnet50(pretrained=True)
model.fc = torch.nn.Linear(2048, num_classes)
\`\`\`

## Results

| Model      | Accuracy | F1 Score |
|------------|----------|----------|
| ResNet-50  | 94.3%    | 0.941    |
| VGG-16     | 91.2%    | 0.909    |
| Custom CNN | 87.5%    | 0.872    |

## Conclusion

Deep learning significantly outperforms classical methods for astronomical classification tasks.
    `,
    content_zh: `
# 用于天文图像分类的深度学习

## 摘要

本研究探索将**卷积神经网络（CNN）**应用于从望远镜图像中分类天文对象，在基准数据集上达到了94.3%的准确率。

## 方法论

我们在Galaxy Zoo数据集上训练了ResNet-50模型：

- 270,000张有标签的星系图像
- 数据增强：旋转、翻转、色彩抖动
- 基于ImageNet权重的迁移学习

\`\`\`python
import torch, torchvision
model = torchvision.models.resnet50(pretrained=True)
model.fc = torch.nn.Linear(2048, num_classes)
\`\`\`

## 结果

| 模型      | 准确率 | F1分数 |
|-----------|--------|--------|
| ResNet-50 | 94.3%  | 0.941  |
| VGG-16    | 91.2%  | 0.909  |
| 自定义CNN | 87.5%  | 0.872  |

## 结论

深度学习在天文分类任务中显著优于传统方法。
    `
  }
];

window.SITE_DATA.blogs = [
  {
    id: "blog-3",
    emoji: "\ud83d\ude80",
    image: "",
    date: "2025-03-20",
    title: "My Journey Setting Up a Home Observatory",
    title_zh: "\u6211\u642d\u5efa\u5bb6\u5ead\u5929\u6587\u53f0\u7684\u5386\u7a0b",
    excerpt: "From a cheap refractor to a motorized equatorial mount \u2014 how I built my backyard observatory step by step.",
    excerpt_zh: "\u4ece\u4e00\u53f0\u5ec9\u4ef7\u6298\u5c04\u671b\u8fdc\u955c\u5230\u7535\u52a8\u8d64\u9053\u4eea\u2014\u2014\u6211\u662f\u5982\u4f55\u4e00\u6b65\u6b65\u642d\u5efa\u540e\u9662\u5929\u6587\u53f0\u7684\u3002",
    content: `
# My Journey Setting Up a Home Observatory

It started with a **$89 refractor telescope** on a wobbly tripod. Three years later, I'm imaging galaxies from my backyard.

## Phase 1: The Humble Beginning

My first night with a real telescope was humbling. I couldn't even find Jupiter.

## Phase 2: Getting Serious

After joining my local astronomy club, I learned:

1. Light pollution maps are essential
2. A goto mount changes everything
3. **Astrophotography** requires patience above all

## Phase 3: The Current Setup

- **OTA**: Explore Scientific 102mm APO
- **Mount**: Sky-Watcher EQ6-R Pro
- **Camera**: ZWO ASI294MC Pro
- **Software**: PixInsight + NINA

Clear skies! 🌟
    `,
    content_zh: `
# 我搭建家庭天文台的历程

一切从一台**89美元的折射望远镜**和一个摇摇晃晃的三脚架开始。三年后，我已经在后院拍摄星系了。

## 第一阶段：谦逊的开始

用真正望远镜的第一个夜晚让我感到谦卑。我甚至找不到木星。

## 第二阶段：认真起来

1. 光污染地图至关重要
2. 自动导向赤道仪改变了一切
3. **天文摄影**最需要的是耐心

## 第三阶段：当前配置

- **镜筒**：Explore Scientific 102mm APO
- **赤道仪**：Sky-Watcher EQ6-R Pro
- **相机**：ZWO ASI294MC Pro
- **软件**：PixInsight + NINA

晴空万里！🌟
    `
  }
];